import type { Metadata } from "next";
import "./globals.css";
import UserInfo from "@/components/userInfo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserInfo/>
        {children}</body>
    </html>
  );
}
